name = "GyreInABox"
uuid = "d40f67ff-4a83-48da-8213-065d3ac3739e"
authors = ["Matt Graham and contributors"]
version = "0.1.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
