name = "GyreInABox"
uuid = "d40f67ff-4a83-48da-8213-065d3ac3739e"
version = "0.1.0-DEV"
authors = ["Matt Graham and contributors"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"

[compat]
Aqua = "0.8.14"
CairoMakie = "0.15.7"
DocStringExtensions = "0.9.5"
Oceananigans = "0.101.3"
Printf = "1.10.0"
Random = "1.10.0"
SeawaterPolynomials = "0.3.10"
Test = "1.10.0"
julia = "1.10.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
